FROM quay.io/fedora/fedora-bootc:latest

# Standard metapackages for setting up a standard GUI install
RUN dnf -qy install \
    @core \
    @hardware-support \
    @standard \
    @base-graphical \
    glibc-all-langpacks \
    --exclude dracut-config-rescue \
    --exclude rsyslog

# Drivers and System configuration

    # Networking and bluetooth
    RUN dnf install -qy NetworkManager-wifi
    RUN dnf install -qy bluez

    # Quality of life for gaming
    RUN dnf install -qy wine-ntsync
    RUN dnf install -qy steam-devices

    RUN dnf install -qy flatpak # Duh...

    # For power management
    RUN dnf install -qy tuned-ppd

    ## Printers
    RUN dnf install -qy cups cups-filters 

    ## Install nvidia drivers
    RUN dnf install -qy https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    RUN dnf install -qy xorg-x11-drv-nvidia-cuda

    # Force akmods to built
    RUN dnf install -qy dkms
    COPY --chmod=755 build-akmods.sh /tmp
    RUN /tmp/build-akmods.sh
    RUN rm -fr /tmp/bin /tmp/build-akmods.sh /tmp/fake-uname /tmp/akmods

    # Remove akmod build tools
    ## [NOTE] The expectation is that the kmod is already built, so we really don't need this anymore
    RUN dnf remove -qy akmod-nvidia dkms
    RUN dnf -qy autoremove
    RUN userdel akmods


    # Inject kargs to prevent nouveau/nova modules from being loaded
    COPY --chmod=755 usr/lib/bootc/kargs.d/nvidia.toml /usr/lib/bootc/kargs.d/nvidia.toml

    # Nvidia container integration using CDI
    RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
        tee /etc/yum.repos.d/nvidia-container-toolkit.repo
    RUN dnf install -qy nvidia-container-toolkit-base

    RUN dnf install -qy ibus-panel ibus-libpinyin

# Setup compositor
RUN dnf install -qy niri --setopt=install_weak_deps=False 
RUN dnf install -qy xdg-desktop-portal-gtk xdg-desktop-portal-gnome gnome-keyring nautilus "gvfs-*"
RUN dnf install -qy noctalia
# [TODO] Try out umbriel compositor?

# Some AppImages (osu) are still using the FUSE v2 runtime
RUN dnf install -qy fuse fuse-libs

# Fonts and themes
RUN dnf install -qy default-fonts fontawesome-fonts-all gnome-icon-theme adw-gtk3-theme google-noto-color-emoji-fonts

# Utilities
RUN dnf install -qy git-credential-libsecret git-credential-oauth pinentry-gnome3 gnupg2-scdaemon
RUN dnf install -qy podman-compose
RUN dnf install -qy foot fish

# Terra utilities
RUN dnf install -qy --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release
RUN dnf install -qy starship
RUN dnf install -qy lazygit git-delta

# Greeter

RUN dnf install -qy noctalia-greeter
RUN mkdir /var/lib/noctalia-greeter
RUN chown greetd /var/lib/noctalia-greeter

COPY --chown=greetd etc/greetd /etc/greetd/
RUN systemctl enable greetd

RUN authselect enable-feature with-systemd-homed
RUN systemctl enable systemd-homed

RUN dnf clean all

RUN rm -rf /var/log/* &&\
    rm -rf /var/cache/*

RUN bootc container lint --no-truncate

