FROM quay.io/fedora/fedora-bootc:latest

RUN dnf upgrade -y

# Standard metapackages for setting up a standard GUI install
RUN dnf -y install \
    @core \
    @hardware-support \
    @standard \
    @base-graphical \
    glibc-all-langpacks \
    --exclude dracut-config-rescue

# add default groups
RUN groupadd plugdev

# Drivers and System configuration
RUN dnf install -y wine-ntsync
RUN dnf install -y steam-devices
RUN dnf install -y flatpak

## Install nvidia drivers
RUN dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
RUN dnf install -y xorg-x11-drv-nvidia-cuda

# Nvidia container integration using CDI
RUN curl -s -L https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo | \
    tee /etc/yum.repos.d/nvidia-container-toolkit.repo
RUN dnf install -y nvidia-container-toolkit-base

# Setup compositor
RUN dnf install -y niri --setopt=install_weak_deps=False 
RUN dnf install -y noctalia
# [TODO] Display manager needs to be added (maybe noctalia greeter?)
# [TODO] Try out umbriel compositor?

RUN dnf install -y xorg-x11-drv-nvidia-cuda

# Some AppImages (osu) are still using the FUSE v2 runtime
RUN dnf install -y fuse fuse-libs

# Utilities
RUN dnf install -y git-credential-libsecret git-credential-oauth
RUN dnf install -y ibus-panel
RUN dnf install -y podman-compose
RUN dnf install -y foot

# Terra utilities
RUN dnf install -y --nogpgcheck --repofrompath 'terra,https://repos.fyralabs.com/terra$releasever' terra-release
RUN dnf install -y starship
RUN dnf install -y lazygit git-delta
RUN dnf install -y noctalia-greeter


# Copy basic configuration
COPY etc /usr/etc/

RUN systemctl enable greetd

RUN authselect enable-feature with-systemd-homed
RUN systemctl enable systemd-homed

RUN dnf clean all
