name: bouquet-publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '00 00 * * *'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        run: echo ${{ secrets.GITHUB_TOKEN }} | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - id: unload-apparmor-profiles
        name: Unload all AppArmor profiles
        # The || true is currently necessary because of a bug in
        # aa-teardown.  See
        # https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/2093797
        # for more details.
        run: sudo aa-teardown || true
        shell: bash -Eueo pipefail -x {0}

      - id: disable-apparmor
        name: Disable and stop AppArmor systemd service
        run: sudo systemctl disable --now apparmor.service
        shell: bash -Eueo pipefail -x {0}

      - name: Build bootc image
        id: build-bootc
        shell: bash
        run: podman build --cap-add=all --security-opt=label=type:container_runtime_t --device /dev/fuse -f Containerfile -t localhost/bouquet-bootc:latest

      - name: Rechunk bootc image # Adapted from universal-blue rechunk justfile
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash -Eueo pipefail -x {0}
        run: |
          IMG=localhost/bouquet-bootc:latest
          CHUNKAH_OUTPUT_DIR=$(mktemp -d)
          export CHUNKAH_CONFIG_STR="$(podman inspect $IMG)"
          podman run --rm --mount=type=image,src=$IMG,dest=/chunkah \
            -v "${CHUNKAH_OUTPUT_DIR}:/run/out:Z" \
            -e CHUNKAH_CONFIG_STR quay.io/coreos/chunkah build \
            -t ghcr.io/lumpbloom7/bouquet-bootc:latest \
            --compressed \
            --prune /sysroot/ \
            --max-layers 256 \
            --label ostree.commit- \
            --label ostree.final-diffid- \
            --output oci:/run/out/chunked
                  
          CHUNKED_IMAGE="$(podman pull "oci:${CHUNKAH_OUTPUT_DIR}/chunked")"
          podman tag "${CHUNKED_IMAGE}" "ghcr.io/lumpbloom7/bouquet-bootc:latest"

      - name: Push rechunked bootc image to registry
        if: ${{ github.event_name != 'pull_request' }}
        run: podman push ghcr.io/lumpbloom7/bouquet-bootc:latest