name: bouquet-publish

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '00 00 * * *'
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        run: echo ${{ secrets.GITHUB_TOKEN }} | podman login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build bootc image
        id: build-bootc
        shell: bash
        run: podman build --cap-add=all --security-opt=label=type:container_runtime_t --device /dev/fuse -f Containerfile -t localhost/bouquet-bootc:latest

      - name: Rechunk bootc image
        if: ${{ github.event_name != 'pull_request' }}
        run:  podman run --rm --privileged -v /var/lib/containers:/var/lib/containers:rw quay.io/fedora/fedora-bootc:latest /usr/libexec/bootc-base-imagectl rechunk localhost/bouquet-bootc:latest ghcr.io/lumpbloom7/bouquet-bootc:latest

      - name: Push rechunked bootc image to registry
        if: ${{ github.event_name != 'pull_request' }}
        run: podman push ghcr.io/lumpbloom7/bouquet-bootc:latest